default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  database: probe_nasa_challenge_development
  username: root
  password: root

test:
  <<: *default
  database: probe_nasa_challenge_test
  username: root
  password: root

production:
  <<: *default
  database: probe_nasa_challenge_production
  username: probe_nasa_challenge
  password: <%= ENV['PROBE_NASA_CHALLENGE_DATABASE_PASSWORD'] %>
